### ISSUE TITLE
Selecting checkpoint for evaluation

### ISSUE THREAD

**Issue by olliethomas** [feidfoe/learning-not-to-learn#1]
Hi, thanks for publishing this repository to accompany your CVPR paper. I'm trying to reproduce some of your results as I think it would be an excellent state-of-the-art benchmark for a project I'm working on, but I'm having some trouble training a new model to match the pre-trained checkpoint provided. Were the settings used the same as in the option.py file? Also, I notice that the benchmark checkpoint is from epoch 90, how did you decide to use this checkpoint?
Thanks!

**Comment by feidfoe** [comment]
I'm sorry about my late response! Settings used for pre-training is the same. Since time cost for training is not the matter of interest, I like to train a network over sufficient epoch. The specific number of epoch is not very important, because the network would converge. If your algorithm does not require some early stopping criteria, I recommend you to do the same.
Thanks.

**Comment by olliethomas** [comment]
Thanks!
